#!/usr/bin/env bash
#display information about subdomains

get_dns_records() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record=$(dig +short "$sub"."$domain")
        record_type=$(dig "$sub"."$domain" | awk '/ANSWER SECTION:/ { getline; print $4}')
        echo "The subdomain $sub is a $record_type record and points to $record"
    done
}

# Main script
if [ "$#" -eq 1 ]; then
    domain=$1
    get_dns_records "$domain"
elif [ "$#" -eq 2 ]; then
    domain=$1
    subdomain=$2
    get_dns_records "$domain" "$subdomain"
fi
