#!/usr/bin/env bash
#Installs and configures HAproxy

sudo apt-get update
sudo apt-get install haproxy -y

text_to_append=$(cat <<EOL
frontend ourwebsitefrontend
    bind *:80
    mode http
    default_backend ourwebsiteendpoint

backend ourwebsiteendpoint
  balance roundrobin
  server 531263-web-01 34.232.71.76:80 check
  server 531263-web-02 100.25.17.30:80 check
EOL
)

echo "$text_to_append" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
