#!/usr/bin/env bash
apt update && apt install -y nginx
echo "server {
    listen 80;
    location / {
        return 200 'Hello from Nginx!';
    }
}" > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
