#!/usr/bin/env bash
# Set the desired username for Nginx
NGINX_USER="nginx"
NGINX_CONF="/etc/nginx/nginx.conf"
cp "$NGINX_CONF" "$NGINX_CONF.bak"
sed -i "s/^user .*;$/user $NGINX_USER;/" "$NGINX_CONF"
echo "
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    # Other server block configurations...
}
" > /etc/nginx/sites-available/default
systemctl restart nginx
